### ISSUE TITLE
contractCall battle plan

### ISSUE THREAD

**Issue by jangko** [status-im/nimbus#220]
# contractCall battle plan

During debugging tool development, I noticed some peculiarities in VM internals but at that time I dare not to  touch it. After some preliminary research and investigation on block 49439 using Premix debugging tool, touching the VM internals seems inevitable.

The contractCall fix will consist of several small PRs divided into 3 stages:

**Stage 1**:
- [x] ~laying groundwork for~ VM opcodes automated test. Not only groundwork or POC, it is a full feature VM opcodes tester
- [x] investigate the possibility of macro assembler(not macro of MASM but macro of Nim).
- [x] ~investigate what should be included in json fixtures to test opcodes.~ Data embedded directly in source code
- [x] put assembler ~-dissassembler into tandem~ to test opcodes ~, roundtrip, etc.~ no need to use dissasembler
- [x] each class of opcodes: stack, mem, log, arith, etc must have representative in the test. 

**Stage 2**:
- [x] decipher Yellow Paper math symbols into something friendlier or rephrase it into working code(gas cost section).
- [ ] opcodes 'Call', 'StaticCall', 'DelegateCall', 'CallCode' must be fixed.
- [ ] they should have solid test.
- [x] gas_costs.nim must be fixed and VM fork should be put into consideration.

**Stage 3**:
- [x] contractCall procedure must be fixed, missing account operations must be added.
- [x] block 49439, 49891, 49904, 50111, 50117 and more if possible, should pass validation.
- [x] generate block validation test for them.
- [x] there should be no regression at this point, additional general state test should pass.

Reminder for myself: Proceed with caution. Do not introduce any regression. 
Consider any regression as something intolerable.

**Comment by stefantalpalaru** [comment]
> decipher Yellow Page math symbols into something friendlier or rephrase it into working code(gas cost section).

First, check if it hasn't been done already in https://github.com/chronaeon/beigepaper

**Comment by jangko** [comment]
The beige paper is an amazing piece of work and it makes a lot of things simpler. But it also too shallow when it comes to the VM opcodes definition. Something like

```text
0xf1  CALL  700  7  1  Message-call into an account. The operand order is: gas, to, value, in offset, in size, out offset, out size.
```

definitely insufficient.

**Comment by zah** [comment]
Regarding "Stage 1", it's true that the standard json suite is relatively incomplete, but I'm not sure we need to spend a lot of time creating our own separate testing framework with things like our own EVM assembler. 

If you are confident that this can be implemented in a day or two, it may be a good investment, but otherwise I would look into reusing some of the existing programming languages as Vyper, solidity or [LLL](https://lll-docs.readthedocs.io/en/latest/lll_introduction.html) to produce bytecode sequences that can be entered manually into the existing json format.

**Comment by jangko** [comment]
sure, simpler is better. The LLL compiler looks promising, and it gives me an idea.
I will investigate them along with macro assembler and pick the simplest one.

**Comment by jangko** [comment]
we already have a solid CREATE and *CALL implementation after #449, closing
