### ISSUE TITLE
some notes before migrating to Nim 1.xx

### ISSUE THREAD

**Issue by jangko** [status-im/nimbus#399]
some reminder to ease the transition to Nim 1.xx

- [x] [bncurve](https://github.com/status-im/nim-bncurve) cannot compile because of nim-lang/Nim#12244. Workaround to make it compile is convert all `const` to `let`, but it only increase maintenance cost.
- [x] [stint](https://github.com/status-im/nim-stint) also affected by Nim bug.  
  - [x] See status-im/nim-stint#88 
  - [x] status-im/nim-stint#89
- [x] a const in utils/difficulty.nim  `const bigMin99 = -99.i256` cannot compile because of stint problem no.2. Workaround: write it as `const bigMin99 = 0.i256 - 99.i256`, but it also weird
- [x] static array return type of `modExpInternal` in precompiles.nim can be changed to array only and remove the static keyword.
- [x] because of nim-lang/Nim#8015, we cannot change GasCosts table in gas_costs.nim into a const. On the other hand, Nim v1.xx also disallow a macro to access global let anymore. Workaround: we need to introduce a new GasCostKind const table to let it accessible by `opTableToCaseStmt` compile time proc. It will increase maintenance cost and ugliness, unless we change some design in EVM drastically.
- [x] nim-lang/Nim#12420
if the above issues adressed, we are clear to move to Nim 1.xx

**Comment by mratsim** [comment]
The static keyword in `modExpInternal` can be changed to {.compileTime.}. Iirc the case where {.compileTime.} triggered "Error: request to generate code for .compileTime proc: foo" while static worked was fixed. Can't find the PR but related https://github.com/nim-lang/Nim/issues/8051.

For the gas cost table, we may be able to use
```
let `ResultGasCostsName`*{.compileTime, inject.}: GasCosts = block:
```

https://github.com/status-im/nimbus/blob/78714295dab4ead5e56c0048c46ae07d8bbed91a/nimbus/vm/interpreter/gas_costs.nim#L358-L379

PR that fuzzed the boundary between compileTime and runtime vars: https://github.com/nim-lang/Nim/pull/12128

**Comment by jangko** [comment]
nice

**Comment by arnetheduck** [comment]
> [1:54 PM] BOTgitterirc: <Araq> well regarding #12332, most probably the fix won't be backported

**Comment by narimiran** [comment]
> well regarding #12332, most probably the fix won't be backported

It will be (if no packages break when fixed).

**Comment by arnetheduck** [comment]
> It will be (if no packages break when fixed).

if no packages _you are testing_ break - worth keeping in mind that this is but a small subset, when creating up an upgrade policy for nim.

**Comment by jangko** [comment]
another nasty bug nim-lang/Nim#12420

**Comment by stefantalpalaru** [comment]
@mratsim's suggested fixes applied to Nimbus in this branch: https://github.com/status-im/nimbus/commits/nim_v1

Everything compiles and the tests pass on Linux. Let's see the CI.

**Comment by jangko** [comment]
latest Nim devel branch now can compiles both nimbus and beacon-chain and pass all tests.
closing this issue and we can concentrate to move to Nim 1.0.2
