### ISSUE TITLE
TODO list related to Status nim integration

### ISSUE THREAD

**Issue by kdeme** [status-im/nimbus#406]
Here is a list of items that I deem useful to get Whisper (and underlying protocols) more stable & secure + also get some additional features. 
For the Status nim integration PoC, these are probably not necessary and only definition & implementation of the wrapper/API is needed.

- [ ] EIP-8 checking https://github.com/status-im/nim-eth/issues/109
- [ ] Connection Limiting: https://github.com/status-im/nim-eth/issues/107 & https://github.com/status-im/nim-eth/issues/108
- [ ] More unit tests + further & additional fuzzing on rlpx (& Whisper)
- [ ] Code coverage on these unit tests + perhaps also on fuzzing corpus
- [ ] Stretch: Integration tests with geth whisper implementation
- [ ] Mailserver https://github.com/status-im/nim-eth/issues/102
- [ ] Metrics https://github.com/status-im/nim-eth/issues/110
- [ ] Have a standalone whisper node application (with capabilities such as above mentioned, e.g. mailserver, bootnode, metrics)
- [ ] Per IP peer limiting? https://github.com/status-im/nim-eth/issues/111 
- [ ] Stretch: Peer rating? 
- [ ] Whisper privacy considerations: https://github.com/status-im/nim-eth/issues/105 & https://github.com/status-im/nim-eth/issues/106

**Comment by oskarth** [comment]
Great stuff!

What do you think of Waku mode (with mailserver support) as a possible "trojan horse" to get Nim into the app as an option?

**Comment by kdeme** [comment]
Closing as no longer relevant
