### ISSUE TITLE
EVMC integration roadmap

### ISSUE THREAD

**Issue by jangko** [status-im/nimbus#445]
- [x] implement evmc host
- [ ] implement evmc create/call
- [ ] implement evmc vm exec
- [ ] implement evmc tests
- [ ] documentations
- [ ] build instructions
